default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: the_news_rails_development
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: the_news_rails_test
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>


production:
  primary: &primary_production
    <<: *default
    database: the_news_rails_production
    username: the_news_rails
    password: <%= ENV["THE_NEWS_RAILS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: the_news_rails_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: the_news_rails_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: the_news_rails_production_cable
    migrations_paths: db/cable_migrate
